LICENSE
README.md
aodh-2.0.1.tar.gz
aodh-3.0.1.tar.gz
aodh.SlackBuild
automaton-1.4.0.tar.gz
automaton.SlackBuild
barbican-3.0.0.tar.gz
barbican.SlackBuild
bifrost-2.1.0.tar.gz
bifrost.SlackBuild
ceilometer-7.0.0.tar.gz
ceilometer.SlackBuild
ceilometermiddleware-0.5.1.tar.gz
ceilometermiddleware.SlackBuild
cinder-9.1.0.tar.gz
cinder.SlackBuild
cliff-2.2.0.tar.gz
cliff.SlackBuild
cloudkitty-0.6.1.tar.gz
cloudkitty-dashboard-0.6.1.tar.gz
cloudkitty-dashboard.SlackBuild
cloudkitty.SlackBuild
congress-4.0.0.tar.gz
congress.SlackBuild
debtcollector-1.8.0.tar.gz
debtcollector.SlackBuild
designate-3.0.0.tar.gz
designate-dashboard-3.0.0.tar.gz
designate-dashboard.SlackBuild
designate.SlackBuild
django_openstack_auth-2.4.2.tar.gz
django_openstack_auth.SlackBuild
freezer-3.0.0.tar.gz
freezer-api-3.0.0.tar.gz
freezer-api.SlackBuild
freezer-dr-3.0.0.tar.gz
freezer-dr.SlackBuild
freezer-web-ui-3.0.0.tar.gz
freezer-web-ui.SlackBuild
freezer.SlackBuild
futurist-0.18.0.tar.gz
futurist.SlackBuild
glance-13.0.0.tar.gz
glance.SlackBuild
glance_store-0.18.0.tar.gz
glance_store.SlackBuild
heat-7.0.0.tar.gz
heat.SlackBuild
horizon-10.0.1.tar.gz
horizon.SlackBuild
instack-5.0.0.tar.gz
instack-undercloud-5.1.0.tar.gz
instack-undercloud.SlackBuild
instack.SlackBuild
ironic-6.2.1.tar.gz
ironic-inspector-4.2.0.tar.gz
ironic-inspector.SlackBuild
ironic-lib-2.1.1.tar.gz
ironic-lib.SlackBuild
ironic-python-agent-1.2.1.tar.gz
ironic-python-agent-1.5.0.tar.gz
ironic-python-agent.SlackBuild
ironic-ui-2.1.0.tar.gz
ironic-ui.SlackBuild
ironic.SlackBuild
keystone-10.0.0.tar.gz
keystone-9.0.2.tar.gz
keystone.SlackBuild
keystoneauth-2.12.2.tar.gz
keystoneauth1-2.4.1.tar.gz
keystonemiddleware-4.4.1.tar.gz
keystonemiddleware-4.9.0.tar.gz
keystonemiddleware.SlackBuild
kolla-3.0.1.tar.gz
kolla.SlackBuild
magnum-3.1.1.tar.gz
magnum-ui-2.1.1.tar.gz
magnum-ui.SlackBuild
magnum.SlackBuild
manila-3.0.0.tar.gz
manila-ui-2.5.1.tar.gz
manila-ui.SlackBuild
manila.SlackBuild
mistral-3.0.2.tar.gz
mistral-dashboard-3.0.2.tar.gz
mistral-dashboard.SlackBuild
mistral.SlackBuild
monasca-agent-1.3.0.tar.gz
monasca-agent.SlackBuild
monasca-api-1.3.1.tar.gz
monasca-api.SlackBuild
monasca-common-1.1.0.tar.gz
monasca-common.SlackBuild
monasca-log-api-1.1.0.tar.gz
monasca-log-api.SlackBuild
monasca-notification-1.4.0.tar.gz
monasca-notification.SlackBuild
monasca-persister-1.1.0.tar.gz
monasca-persister.SlackBuild
monasca-statsd-1.2.1.tar.gz
monasca-statsd.SlackBuild
monasca-ui-1.2.1.tar.gz
monasca-ui.SlackBuild
mox3-0.18.0.tar.gz
mox3.SlackBuild
murano-3.0.0.tar.gz
murano-agent-3.0.0.tar.gz
murano-agent.SlackBuild
murano-dashboard-3.0.0.tar.gz
murano-dashboard.SlackBuild
murano.SlackBuild
networking-hyperv-3.0.0.tar.gz
networking-hyperv.SlackBuild
networking-ovn-1.0.0.tar.gz
networking-ovn.SlackBuild
neutron-9.1.0.tar.gz
neutron-dynamic-routing-9.0.0.tar.gz
neutron-dynamic-routing.SlackBuild
neutron-fwaas-9.0.0.tar.gz
neutron-fwaas.SlackBuild
neutron-lbaas-9.1.0.tar.gz
neutron-lbaas.SlackBuild
neutron-lib-0.4.0.tar.gz
neutron-lib.SlackBuild
neutron-vpnaas-9.0.0.tar.gz
neutron-vpnaas.SlackBuild
neutron.SlackBuild
nova-14.0.2.tar.gz
nova.SlackBuild
octavia-0.9.0.tar.gz
octavia.SlackBuild
os-apply-config-5.0.0.tar.gz
os-apply-config.SlackBuild
os-brick-1.6.1.tar.gz
os-brick.SlackBuild
os-client-config-1.21.1.tar.gz
os-client-config.SlackBuild
os-cloud-config-5.0.0.tar.gz
os-cloud-config.SlackBuild
os-collect-config-5.0.0.tar.gz
os-collect-config.SlackBuild
os-net-config-5.0.0.tar.gz
os-net-config.SlackBuild
os-refresh-config-5.0.0.tar.gz
os-refresh-config.SlackBuild
os-vif-1.2.1.tar.gz
os-vif.SlackBuild
os-win-1.2.1.tar.gz
os-win.SlackBuild
osc-lib-1.1.0.tar.gz
osc-lib.SlackBuild
oslo.cache-1.14.0.tar.gz
oslo.cache.SlackBuild
oslo.concurrency-3.14.0.tar.gz
oslo.concurrency.SlackBuild
oslo.config-3.17.0.tar.gz
oslo.config.SlackBuild
oslo.context-2.9.0.tar.gz
oslo.context.SlackBuild
oslo.db-4.13.3.tar.gz
oslo.db.SlackBuild
oslo.i18n-3.9.0.tar.gz
oslo.i18n.SlackBuild
oslo.log-3.16.0.tar.gz
oslo.log.SlackBuild
oslo.messaging-5.10.0.tar.gz
oslo.messaging.SlackBuild
oslo.middleware-3.19.0.tar.gz
oslo.middleware.SlackBuild
oslo.policy-1.14.0.tar.gz
oslo.policy.SlackBuild
oslo.privsep-1.13.0.tar.gz
oslo.privsep.SlackBuild
oslo.reports-1.14.0.tar.gz
oslo.reports.SlackBuild
oslo.rootwrap-5.1.1.tar.gz
oslo.rootwrap.SlackBuild
oslo.serialization-2.13.0.tar.gz
oslo.serialization.SlackBuild
oslo.service-1.16.0.tar.gz
oslo.service.SlackBuild
oslo.utils-3.16.0.tar.gz
oslo.utils.SlackBuild
oslo.versionedobjects-1.17.0.tar.gz
oslo.versionedobjects.SlackBuild
oslo.vmware-2.14.0.tar.gz
oslo.vmware.SlackBuild
oslosphinx-4.7.0.tar.gz
oslosphinx.SlackBuild
oslotest-2.10.0.tar.gz
oslotest.SlackBuild
osprofiler-1.4.0.tar.gz
osprofiler.SlackBuild
panko-1.0.0.tar.gz
panko.SlackBuild
puppet-aodh-9.4.1.tar.gz
puppet-aodh.SlackBuild
puppet-barbican-9.4.0.tar.gz
puppet-barbican.SlackBuild
puppet-ceilometer-9.4.1.tar.gz
puppet-ceilometer.SlackBuild
puppet-ceph-2.2.1.tar.gz
puppet-ceph.SlackBuild
puppet-cinder-9.4.1.tar.gz
puppet-cinder.SlackBuild
puppet-designate-9.4.0.tar.gz
puppet-designate.SlackBuild
puppet-glance-9.4.0.tar.gz
puppet-glance.SlackBuild
puppet-gnocchi-9.4.1.tar.gz
puppet-gnocchi.SlackBuild
puppet-heat-9.4.1.tar.gz
puppet-heat.SlackBuild
puppet-horizon-9.4.1.tar.gz
puppet-horizon.SlackBuild
puppet-ironic-9.4.1.tar.gz
puppet-ironic.SlackBuild
puppet-keystone-9.4.0.tar.gz
puppet-keystone.SlackBuild
puppet-magnum-9.4.0.tar.gz
puppet-magnum.SlackBuild
puppet-manila-9.4.0.tar.gz
puppet-manila.SlackBuild
puppet-mistral-9.4.0.tar.gz
puppet-mistral.SlackBuild
puppet-murano-9.4.0.tar.gz
puppet-murano.SlackBuild
puppet-neutron-9.4.2.tar.gz
puppet-neutron.SlackBuild
puppet-nova-9.4.0.tar.gz
puppet-nova.SlackBuild
puppet-openstack_extras-9.4.0.tar.gz
puppet-openstack_extras.SlackBuild
puppet-openstacklib-9.4.0.tar.gz
puppet-openstacklib.SlackBuild
puppet-oslo-9.4.0.tar.gz
puppet-oslo.SlackBuild
puppet-ovn-9.4.0.tar.gz
puppet-ovn.SlackBuild
puppet-sahara-9.4.0.tar.gz
puppet-sahara.SlackBuild
puppet-swift-9.4.3.tar.gz
puppet-swift.SlackBuild
puppet-tempest-9.4.0.tar.gz
puppet-tempest.SlackBuild
puppet-tripleo-5.4.0.tar.gz
puppet-tripleo.SlackBuild
puppet-trove-9.4.0.tar.gz
puppet-trove.SlackBuild
puppet-vswitch-5.4.0.tar.gz
puppet-vswitch.SlackBuild
puppet-zaqar-9.4.0.tar.gz
puppet-zaqar.SlackBuild
pycadf-2.4.0.tar.gz
pycadf.SlackBuild
python-aodhclient-0.7.0.tar.gz
python-barbicanclient-4.1.0.tar.gz
python-barbicanclient.SlackBuild
python-brick-cinderclient-ext-0.2.0.tar.gz
python-brick-cinderclient-ext.SlackBuild
python-ceilometerclient-2.6.2.tar.gz
python-ceilometerclient.SlackBuild
python-cinderclient-1.9.0.tar.gz
python-cinderclient.SlackBuild
python-cloudkittyclient-0.6.0.tar.gz
python-cloudkittyclient.SlackBuild
python-congressclient-1.5.0.tar.gz
python-congressclient.SlackBuild
python-designateclient-2.3.0.tar.gz
python-designateclient.SlackBuild
python-freezerclient-1.0.0.tar.gz
python-freezerclient.SlackBuild
python-glanceclient-2.5.0.tar.gz
python-glanceclient.SlackBuild
python-heatclient-1.5.0.tar.gz
python-heatclient.SlackBuild
python-ironic-inspector-client-1.9.0.tar.gz
python-ironic-inspector-client.SlackBuild
python-ironicclient-1.7.0.tar.gz
python-ironicclient.SlackBuild
python-keystoneclient-3.5.0.tar.gz
python-keystoneclient.SlackBuild
python-magnumclient-2.3.1.tar.gz
python-magnumclient.SlackBuild
python-manilaclient-1.11.0.tar.gz
python-manilaclient.SlackBuild
python-mistralclient-2.1.1.tar.gz
python-mistralclient.SlackBuild
python-monascaclient-1.2.0.tar.gz
python-monascaclient.SlackBuild
python-muranoclient-0.11.1.tar.gz
python-muranoclient.SlackBuild
python-neutronclient-6.0.0.tar.gz
python-neutronclient.SlackBuild
python-novaclient-6.0.0.tar.gz
python-novaclient.SlackBuild
python-openstackclient-3.2.0.tar.gz
python-openstackclient.SlackBuild
python-saharaclient-0.18.0.tar.gz
python-saharaclient.SlackBuild
python-searchlightclient-1.0.0.tar.gz
python-searchlightclient.SlackBuild
python-senlinclient-1.0.0.tar.gz
python-senlinclient.SlackBuild
python-solumclient-2.1.1.tar.gz
python-solumclient.SlackBuild
python-swiftclient-3.1.0.tar.gz
python-swiftclient.SlackBuild
python-tackerclient-0.7.0.tar.gz
python-tackerclient.SlackBuild
python-tripleoclient-5.4.0.tar.gz
python-tripleoclient.SlackBuild
python-troveclient-2.1.2.tar.gz
python-troveclient-2.5.0.tar.gz
python-troveclient.SlackBuild
python-vitrageclient-1.0.1.tar.gz
python-vitrageclient.SlackBuild
python-watcher-0.31.0.tar.gz
python-watcher.SlackBuild
python-watcherclient-0.25.1.tar.gz
python-watcherclient.SlackBuild
python-zaqarclient-1.2.0.tar.gz
python-zaqarclient.SlackBuild
sahara-5.0.0.tar.gz
sahara-dashboard-5.0.0.tar.gz
sahara-dashboard.SlackBuild
sahara-extra-5.0.0.tar.gz
sahara-extra.SlackBuild
sahara-image-elements-5.0.0.tar.gz
sahara-image-elements.SlackBuild
sahara.SlackBuild
searchlight-0.2.1.tar.gz
searchlight-1.0.0.tar.gz
searchlight-ui-1.0.0.tar.gz
searchlight-ui.SlackBuild
searchlight.SlackBuild
senlin-2.0.0.tar.gz
senlin-dashboard-0.5.0.tar.gz
senlin-dashboard.SlackBuild
senlin.SlackBuild
slackdesc.py
solum-5.0.1.tar.gz
solum-dashboard-1.1.1.tar.gz
solum-dashboard.SlackBuild
solum.SlackBuild
solum_guestagent-1.0.0.tar.gz
solum_guestagent.SlackBuild
stevedore-1.17.1.tar.gz
stevedore.SlackBuild
swift-2.10.0.tar.gz
swift.SlackBuild
t
tacker-0.5.0.tar.gz
tacker-horizon-0.5.0.tar.gz
tacker-horizon.SlackBuild
tacker.SlackBuild
taskflow-2.6.0.tar.gz
taskflow.SlackBuild
tooz-1.43.0.tar.gz
tooz.SlackBuild
tripleo-common-5.4.0.tar.gz
tripleo-common.SlackBuild
tripleo-heat-templates-5.1.0.tar.gz
tripleo-heat-templates.SlackBuild
tripleo-image-elements-5.1.0.tar.gz
tripleo-image-elements.SlackBuild
tripleo-puppet-elements-5.1.0.tar.gz
tripleo-puppet-elements.SlackBuild
tripleo-quickstart-1.0.0.tar.gz
tripleo-quickstart.SlackBuild
tripleo-ui-1.0.5.tar.gz
tripleo-ui.SlackBuild
tripleo-validations-5.1.0.tar.gz
tripleo-validations.SlackBuild
trove-5.0.1.tar.gz
trove-6.0.0.tar.gz
trove-dashboard-6.0.1.tar.gz
trove-dashboard-7.0.0.tar.gz
trove-dashboard.SlackBuild
trove.SlackBuild
vitrage-1.3.0.tar.gz
vitrage-dashboard-1.0.2.tar.gz
vitrage-dashboard.SlackBuild
vitrage.SlackBuild
vmware-nsx-8.0.0.tar.gz
vmware-nsx.SlackBuild
watcher-0.29.0.tar.gz
watcher-dashboard-0.5.0.tar.gz
watcher-dashboard.SlackBuild
watcher.SlackBuild
zaqar-3.0.0.tar.gz
zaqar-ui-1.0.0.tar.gz
zaqar-ui.SlackBuild
zaqar.SlackBuild
